Return no body with 501 status if there's no mapping #114
enonic/nextjs-enonic-starter pull request #131
Opened 2021-12-17 15:08 UTC by pmi

depends on https://github.com/enonic/nextjs-enonic-starter/pull/130

closes #113

2021-12-17 16:33 UTC, espen42 requested changes

2021-12-17 16:33 UTC, espen42 commented on src/xpAdapter/guillotine/fetchContent.ts
> +import enonicConnectionConfig, {XP_COMPONENT_TYPE, XP_RENDER_MODE, XP_REQUEST_TYPE,} from "../enonic-connection-config";
Actually, the point of having these here is to make fetchContent pluggable later (standalone from NPM) without an external dependency to enonic-connection-config.ts. It's better if the dependency is the other way, and this file defines the structures it needs to work and the shape it returns.

2021-12-17 16:33 UTC, espen42 commented on src/xpAdapter/guillotine/fetchContent.ts
> -    const fetchContent: ContentFetcher = async (
Hmm, I disagree here - I'd update and correct this comment instead of removing it, both here and for `buildContentFetcher` above - both the comment and keeping it a named exported function. 

These two functions are the primary things that are exposed from this pretty complex module. We're documenting the API, but I think it should be included here too as much if IDE's can use it and explain/simplify the usage beyond just types.

2021-12-17 16:33 UTC, espen42 commented on src/xpAdapter/guillotine/fetchContent.ts
> +                componentDescriptors[i].component!.data = datas[i];
Another minor thing. Good description of purpose, but maybe still a little untransparent - since componentDescriptors isn't used below this, this must be a mutation of objects that are used by another name somewhere else? Probably not hard at all to figure out by diving into it, but ideally the flow should be  readable at the surface.

2021-12-20 10:39 UTC, pmi commented on src/pages/[[...contentPath]].tsx
> +    if (meta && !meta.canRender) {
Exactly ! This is not an error nor a successful rendering :)
This is needed for CS to understand that next is unable to render it and show controller selector.

2021-12-20 10:53 UTC, pmi commented on src/pages/_app.tsx
> +    if (pageProps.meta?.requestType === XP_REQUEST_TYPE.COMPONENT || !pageProps.meta?.canRender) {
Yes, we're returning empty body and status 501 if we can't render.

2021-12-20 11:09 UTC, pmi commented on src/xpAdapter/TypesRegistry.ts
> +//NB! Always return null or empty object from processor for next is unable to serialize undefined
Well, I haven't tested it a lot, but returning undefined from processor caused problems:
`Error: Error serializing `.page.regions.main.components[1].data` returned from `getServerSideProps` in "/[[...contentPath]]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.`

2021-12-20 11:11 UTC, pmi commented on src/xpAdapter/TypesRegistry.ts
>  interface TypeSelector {
ok, it looks like a `TypeDictionary` then since this is an object with name-definitions entries

2021-12-20 11:13 UTC, pmi commented on src/cms/typesRegistration.ts
> +import {CATCH_ALL_NAME, TypesRegistry} from '../xpAdapter/TypesRegistry';
Well, can not agree, since it is first of all a name which goes to the name field of methods like
```    public static addPart(name: string, obj: TypeDefinition): void {
        return TypesRegistry.addType('part', name, obj);
    }
```

2021-12-20 11:14 UTC, pmi commented on src/pages/[[...contentPath]].tsx
> +export interface ServerSideProps {
Right, this is essentially the same as FetchContentResult indeed !

2021-12-20 11:19 UTC, pmi commented on src/xpAdapter/guillotine/fetchContent.ts
> +import enonicConnectionConfig, {XP_COMPONENT_TYPE, XP_RENDER_MODE, XP_REQUEST_TYPE,} from "../enonic-connection-config";
Can't see your point here, those 3 are still imported from enonic-connection-config as before

2021-12-20 11:43 UTC, pmi commented on src/xpAdapter/guillotine/fetchContent.ts
> +                componentDescriptors[i].component!.data = datas[i];
componentDescriptors are not used, but components are, and since descriptors have references to components from the components array, updating descriptors is essentially the same as updating components array with data, but without the need to do searches for every component in the array.

2021-12-20 11:49 UTC, pmi commented on src/cms/typesRegistration.ts
> +    processor: processListPropsExample,
Reverted

2021-12-20 11:51 UTC, pmi commented on src/xpAdapter/guillotine/fetchContent.ts
> -    const fetchContent: ContentFetcher = async (
Brought comments back

2021-12-20 14:10 UTC, espen42 commented on src/xpAdapter/guillotine/fetchContent.ts
> +import enonicConnectionConfig, {XP_COMPONENT_TYPE, XP_RENDER_MODE, XP_REQUEST_TYPE,} from "../enonic-connection-config";
Uh, you're right. Don't know what I was thinking. :D

2021-12-20 14:14 UTC, espen42 commented on src/xpAdapter/guillotine/fetchContent.ts
> +                componentDescriptors[i].component!.data = datas[i];
Sure, that's the mutation I meant. But it just needs a quick comment in the code (where are the `components` unpacked and used) to be transparent and fast for others to grok, instead of needing the readers to track down the usage themselves.

2021-12-20 14:16 UTC, espen42 approved these changes

2021-12-20 14:25 UTC, espen42 approved these changes

2021-12-20 14:25 UTC, espen42 commented on src/xpAdapter/views/_BaseContent.tsx
> +    const typeDef = TypesRegistry.getContentType(meta.type);
I'm getting a TS build error here now (on `npm run build`): `Type error: Object is possibly 'null'`, and it points to `meta`. Same on line 28 with meta.canRender. Adding a `meta!` fixes this, but then others appear. 

Needs a TS polish, but maybe we can postpone that for the very final step?

2021-12-21 08:18 UTC, pmi commented on src/xpAdapter/views/_BaseContent.tsx
> +    const typeDef = TypesRegistry.getContentType(meta.type);
Good catch ! It seems I overlooked something in dev mode, will try to fix it before merging !

2021-12-21 09:33 UTC, merged